// Code generated by protoc-gen-go. DO NOT EDIT.
// source: buildserver.proto

/*
Package buildserver is a generated protocol buffer package.

It is generated from these files:
	buildserver.proto

It has these top-level messages:
	Version
	VersionRequest
	VersionResponse
*/
package buildserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import gobuildslave "github.com/brotherlogic/gobuildslave/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Version struct {
	Job     *gobuildslave.Job `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
	Version string            `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Path    string            `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Server  string            `protobuf:"bytes,4,opt,name=server" json:"server,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Version) GetJob() *gobuildslave.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *Version) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Version) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Version) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

type VersionRequest struct {
	JustLatest bool              `protobuf:"varint,1,opt,name=just_latest,json=justLatest" json:"just_latest,omitempty"`
	Job        *gobuildslave.Job `protobuf:"bytes,2,opt,name=job" json:"job,omitempty"`
}

func (m *VersionRequest) Reset()                    { *m = VersionRequest{} }
func (m *VersionRequest) String() string            { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()               {}
func (*VersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VersionRequest) GetJustLatest() bool {
	if m != nil {
		return m.JustLatest
	}
	return false
}

func (m *VersionRequest) GetJob() *gobuildslave.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type VersionResponse struct {
	Versions []*Version `protobuf:"bytes,1,rep,name=versions" json:"versions,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VersionResponse) GetVersions() []*Version {
	if m != nil {
		return m.Versions
	}
	return nil
}

func init() {
	proto.RegisterType((*Version)(nil), "buildserver.Version")
	proto.RegisterType((*VersionRequest)(nil), "buildserver.VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "buildserver.VersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BuildService service

type BuildServiceClient interface {
	GetVersions(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type buildServiceClient struct {
	cc *grpc.ClientConn
}

func NewBuildServiceClient(cc *grpc.ClientConn) BuildServiceClient {
	return &buildServiceClient{cc}
}

func (c *buildServiceClient) GetVersions(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/buildserver.BuildService/GetVersions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BuildService service

type BuildServiceServer interface {
	GetVersions(context.Context, *VersionRequest) (*VersionResponse, error)
}

func RegisterBuildServiceServer(s *grpc.Server, srv BuildServiceServer) {
	s.RegisterService(&_BuildService_serviceDesc, srv)
}

func _BuildService_GetVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).GetVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buildserver.BuildService/GetVersions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).GetVersions(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BuildService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "buildserver.BuildService",
	HandlerType: (*BuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersions",
			Handler:    _BuildService_GetVersions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buildserver.proto",
}

func init() { proto.RegisterFile("buildserver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0x53, 0xda, 0x3a, 0x11, 0xa5, 0x8b, 0xc8, 0x52, 0x05, 0x43, 0xbc, 0xe4, 0x94,
	0x48, 0x04, 0x7f, 0x80, 0x1e, 0x84, 0xe2, 0x29, 0x42, 0x0f, 0x5e, 0x24, 0x1b, 0x87, 0x24, 0x25,
	0x76, 0xe3, 0xee, 0x24, 0xbf, 0x5f, 0xb2, 0x9b, 0x94, 0x1c, 0x8a, 0xb7, 0x99, 0x37, 0xef, 0xcd,
	0x7e, 0x3b, 0xb0, 0x16, 0x6d, 0x55, 0x7f, 0x6b, 0x54, 0x1d, 0xaa, 0xa8, 0x51, 0x92, 0x24, 0xf3,
	0x26, 0xd2, 0xe6, 0xb9, 0xa8, 0xa8, 0x6c, 0x45, 0x94, 0xcb, 0x9f, 0x58, 0x28, 0x49, 0x25, 0xaa,
	0x5a, 0x16, 0x55, 0x1e, 0x17, 0xd2, 0xda, 0xea, 0xac, 0xc3, 0xd8, 0x04, 0x63, 0x53, 0xdb, 0x25,
	0x01, 0xc1, 0x72, 0x87, 0x4a, 0x57, 0xf2, 0xc0, 0x1e, 0xc0, 0xdd, 0x4b, 0xc1, 0x1d, 0xdf, 0x09,
	0xbd, 0x64, 0x1d, 0x4d, 0x83, 0xd1, 0x56, 0x8a, 0xb4, 0x9f, 0x32, 0x0e, 0xcb, 0xce, 0xfa, 0xf9,
	0xcc, 0x77, 0xc2, 0xf3, 0x74, 0x6c, 0x19, 0x83, 0x79, 0x93, 0x51, 0xc9, 0x5d, 0x23, 0x9b, 0x9a,
	0xdd, 0xc0, 0xc2, 0xf2, 0xf1, 0xb9, 0x51, 0x87, 0x2e, 0xd8, 0xc1, 0xe5, 0xf0, 0x6a, 0x8a, 0xbf,
	0x2d, 0x6a, 0x62, 0xf7, 0xe0, 0xed, 0x5b, 0x4d, 0x5f, 0x75, 0x46, 0xa8, 0xc9, 0x40, 0xac, 0x52,
	0xe8, 0xa5, 0x77, 0xa3, 0x8c, 0x74, 0xb3, 0xff, 0xe8, 0x82, 0x57, 0xb8, 0x3a, 0xee, 0xd5, 0x8d,
	0x3c, 0x68, 0x64, 0x8f, 0xb0, 0x1a, 0x08, 0x35, 0x77, 0x7c, 0x37, 0xf4, 0x92, 0xeb, 0x68, 0x7a,
	0xcb, 0xd1, 0x7f, 0x74, 0x25, 0x9f, 0x70, 0xf1, 0xd2, 0x1b, 0x3e, 0x50, 0x75, 0x55, 0x8e, 0x6c,
	0x0b, 0xde, 0x1b, 0xd2, 0xe0, 0xd3, 0xec, 0xf6, 0x64, 0xdc, 0x7e, 0x63, 0x73, 0x77, 0x7a, 0x68,
	0x59, 0x82, 0x33, 0xb1, 0x30, 0x57, 0x7f, 0xfa, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x89, 0xff,
	0x43, 0xcf, 0x01, 0x00, 0x00,
}
