// Code generated by protoc-gen-go. DO NOT EDIT.
// source: buildserver.proto

package buildserver

import (
	fmt "fmt"
	proto1 "github.com/brotherlogic/gobuildslave/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Crash struct {
	ErrorMessage         string   `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Crash) Reset()         { *m = Crash{} }
func (m *Crash) String() string { return proto.CompactTextString(m) }
func (*Crash) ProtoMessage()    {}
func (*Crash) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8d4ba165a6f854, []int{0}
}

func (m *Crash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Crash.Unmarshal(m, b)
}
func (m *Crash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Crash.Marshal(b, m, deterministic)
}
func (m *Crash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Crash.Merge(m, src)
}
func (m *Crash) XXX_Size() int {
	return xxx_messageInfo_Crash.Size(m)
}
func (m *Crash) XXX_DiscardUnknown() {
	xxx_messageInfo_Crash.DiscardUnknown(m)
}

var xxx_messageInfo_Crash proto.InternalMessageInfo

func (m *Crash) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type Version struct {
	Job                  *proto1.Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Version              string      `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Path                 string      `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Server               string      `protobuf:"bytes,4,opt,name=server,proto3" json:"server,omitempty"`
	VersionDate          int64       `protobuf:"varint,5,opt,name=version_date,json=versionDate,proto3" json:"version_date,omitempty"`
	Crashes              []*Crash    `protobuf:"bytes,6,rep,name=crashes,proto3" json:"crashes,omitempty"`
	GithubHash           string      `protobuf:"bytes,7,opt,name=github_hash,json=githubHash,proto3" json:"github_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8d4ba165a6f854, []int{1}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetJob() *proto1.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *Version) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Version) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Version) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *Version) GetVersionDate() int64 {
	if m != nil {
		return m.VersionDate
	}
	return 0
}

func (m *Version) GetCrashes() []*Crash {
	if m != nil {
		return m.Crashes
	}
	return nil
}

func (m *Version) GetGithubHash() string {
	if m != nil {
		return m.GithubHash
	}
	return ""
}

type VersionRequest struct {
	JustLatest           bool        `protobuf:"varint,1,opt,name=just_latest,json=justLatest,proto3" json:"just_latest,omitempty"`
	Job                  *proto1.Job `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8d4ba165a6f854, []int{2}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

func (m *VersionRequest) GetJustLatest() bool {
	if m != nil {
		return m.JustLatest
	}
	return false
}

func (m *VersionRequest) GetJob() *proto1.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type VersionResponse struct {
	Versions             []*Version `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8d4ba165a6f854, []int{3}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersions() []*Version {
	if m != nil {
		return m.Versions
	}
	return nil
}

type BuildRequest struct {
	Job                  *proto1.Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BuildRequest) Reset()         { *m = BuildRequest{} }
func (m *BuildRequest) String() string { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()    {}
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8d4ba165a6f854, []int{4}
}

func (m *BuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest.Unmarshal(m, b)
}
func (m *BuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest.Marshal(b, m, deterministic)
}
func (m *BuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest.Merge(m, src)
}
func (m *BuildRequest) XXX_Size() int {
	return xxx_messageInfo_BuildRequest.Size(m)
}
func (m *BuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest proto.InternalMessageInfo

func (m *BuildRequest) GetJob() *proto1.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type BuildResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8d4ba165a6f854, []int{5}
}

func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (m *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(m, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

type CrashRequest struct {
	Job                  *proto1.Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Version              string      `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Crash                *Crash      `protobuf:"bytes,2,opt,name=crash,proto3" json:"crash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CrashRequest) Reset()         { *m = CrashRequest{} }
func (m *CrashRequest) String() string { return proto.CompactTextString(m) }
func (*CrashRequest) ProtoMessage()    {}
func (*CrashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8d4ba165a6f854, []int{6}
}

func (m *CrashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrashRequest.Unmarshal(m, b)
}
func (m *CrashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrashRequest.Marshal(b, m, deterministic)
}
func (m *CrashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrashRequest.Merge(m, src)
}
func (m *CrashRequest) XXX_Size() int {
	return xxx_messageInfo_CrashRequest.Size(m)
}
func (m *CrashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrashRequest proto.InternalMessageInfo

func (m *CrashRequest) GetJob() *proto1.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *CrashRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CrashRequest) GetCrash() *Crash {
	if m != nil {
		return m.Crash
	}
	return nil
}

type CrashResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrashResponse) Reset()         { *m = CrashResponse{} }
func (m *CrashResponse) String() string { return proto.CompactTextString(m) }
func (*CrashResponse) ProtoMessage()    {}
func (*CrashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8d4ba165a6f854, []int{7}
}

func (m *CrashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrashResponse.Unmarshal(m, b)
}
func (m *CrashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrashResponse.Marshal(b, m, deterministic)
}
func (m *CrashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrashResponse.Merge(m, src)
}
func (m *CrashResponse) XXX_Size() int {
	return xxx_messageInfo_CrashResponse.Size(m)
}
func (m *CrashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrashResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Crash)(nil), "buildserver.Crash")
	proto.RegisterType((*Version)(nil), "buildserver.Version")
	proto.RegisterType((*VersionRequest)(nil), "buildserver.VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "buildserver.VersionResponse")
	proto.RegisterType((*BuildRequest)(nil), "buildserver.BuildRequest")
	proto.RegisterType((*BuildResponse)(nil), "buildserver.BuildResponse")
	proto.RegisterType((*CrashRequest)(nil), "buildserver.CrashRequest")
	proto.RegisterType((*CrashResponse)(nil), "buildserver.CrashResponse")
}

func init() { proto.RegisterFile("buildserver.proto", fileDescriptor_cd8d4ba165a6f854) }

var fileDescriptor_cd8d4ba165a6f854 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x51, 0x6b, 0xdb, 0x30,
	0x10, 0xae, 0xeb, 0x26, 0xe9, 0xce, 0xe9, 0x4a, 0x8f, 0x31, 0xd4, 0x6c, 0xb0, 0x4c, 0x7d, 0xc9,
	0x43, 0x71, 0x46, 0x0a, 0x7b, 0x1e, 0xeb, 0xd8, 0x46, 0xd9, 0x5e, 0x3c, 0xe8, 0x6b, 0x90, 0xd3,
	0x23, 0x76, 0x49, 0xab, 0x4c, 0x52, 0xbc, 0x3f, 0x3c, 0xf6, 0x3b, 0x86, 0x4f, 0x72, 0xb0, 0xc1,
	0x8c, 0xf5, 0x4d, 0xfa, 0xf4, 0xdd, 0x77, 0xf7, 0x7d, 0x87, 0xe0, 0x2c, 0xdf, 0x95, 0x9b, 0x3b,
	0x4b, 0xa6, 0x22, 0x93, 0x6e, 0x8d, 0x76, 0x1a, 0x93, 0x16, 0x34, 0x79, 0xbf, 0x2e, 0x5d, 0xb1,
	0xcb, 0xd3, 0x95, 0x7e, 0x98, 0xe7, 0x46, 0xbb, 0x82, 0xcc, 0x46, 0xaf, 0xcb, 0xd5, 0x7c, 0xad,
	0x3d, 0x6d, 0xa3, 0x2a, 0x9a, 0x73, 0xe1, 0x9c, 0xcf, 0x5e, 0x44, 0x5e, 0xc2, 0xe0, 0xda, 0x28,
	0x5b, 0xe0, 0x05, 0x9c, 0x90, 0x31, 0xda, 0x2c, 0x1f, 0xc8, 0x5a, 0xb5, 0x26, 0x11, 0x4d, 0xa3,
	0xd9, 0xb3, 0x6c, 0xcc, 0xe0, 0x77, 0x8f, 0xc9, 0x3f, 0x11, 0x8c, 0x6e, 0xc9, 0xd8, 0x52, 0x3f,
	0xe2, 0x05, 0xc4, 0xf7, 0x3a, 0x67, 0x5a, 0xb2, 0x38, 0x4b, 0xdb, 0x7d, 0xd2, 0x1b, 0x9d, 0x67,
	0xf5, 0x2b, 0x0a, 0x18, 0x55, 0x9e, 0x2f, 0x0e, 0x59, 0xaf, 0xb9, 0x22, 0xc2, 0xd1, 0x56, 0xb9,
	0x42, 0xc4, 0x0c, 0xf3, 0x19, 0x5f, 0xc2, 0xd0, 0xdb, 0x11, 0x47, 0x8c, 0x86, 0x1b, 0xbe, 0x85,
	0x71, 0x28, 0x5b, 0xde, 0x29, 0x47, 0x62, 0x30, 0x8d, 0x66, 0x71, 0x96, 0x04, 0xec, 0x93, 0x72,
	0x84, 0x97, 0x30, 0x5a, 0xd5, 0x3e, 0xc8, 0x8a, 0xe1, 0x34, 0x9e, 0x25, 0x0b, 0x4c, 0xdb, 0x89,
	0xb1, 0xc7, 0xac, 0xa1, 0xe0, 0x1b, 0x48, 0x7c, 0x5e, 0xcb, 0x42, 0xd9, 0x42, 0x8c, 0xb8, 0x1b,
	0x78, 0xe8, 0xab, 0xb2, 0x85, 0xbc, 0x85, 0xe7, 0xc1, 0x67, 0x46, 0x3f, 0x77, 0x64, 0x5d, 0x5d,
	0x72, 0xbf, 0xb3, 0x6e, 0xb9, 0x51, 0x8e, 0xac, 0x63, 0xdb, 0xc7, 0x19, 0xd4, 0xd0, 0x37, 0x46,
	0x9a, 0x3c, 0x0e, 0xff, 0x95, 0x87, 0xbc, 0x86, 0xd3, 0xbd, 0xae, 0xdd, 0xea, 0x47, 0x4b, 0xf8,
	0x0e, 0x8e, 0x83, 0x11, 0x2b, 0x22, 0x1e, 0xfd, 0x45, 0x67, 0xf4, 0x86, 0xbf, 0x67, 0xc9, 0x2b,
	0x18, 0x7f, 0xac, 0x09, 0xcd, 0x68, 0xff, 0xb3, 0x09, 0x79, 0x0a, 0x27, 0xa1, 0xc8, 0xf7, 0x95,
	0xbf, 0x60, 0xec, 0x53, 0x79, 0x82, 0x4a, 0x7b, 0x9f, 0x71, 0x77, 0x9f, 0x33, 0x18, 0x70, 0xba,
	0x21, 0x80, 0xbe, 0xf8, 0x3d, 0xa1, 0x9e, 0x24, 0x34, 0xf6, 0x93, 0x2c, 0x7e, 0x47, 0xc1, 0xd0,
	0x0f, 0x32, 0x55, 0xb9, 0x22, 0xfc, 0x00, 0x03, 0xbe, 0xe3, 0x79, 0x47, 0xa5, 0x6d, 0x7a, 0x32,
	0xe9, 0x7b, 0x0a, 0xd6, 0x0e, 0xf0, 0x06, 0x92, 0x2f, 0xe4, 0x42, 0x74, 0x16, 0x5f, 0xf5, 0x26,
	0x1a, 0x94, 0x5e, 0xf7, 0x3f, 0xee, 0xb5, 0x3e, 0x43, 0x92, 0xd1, 0x56, 0x1b, 0xe7, 0x3f, 0xca,
	0x79, 0x8f, 0xb3, 0xde, 0x99, 0x3a, 0x26, 0xe5, 0x41, 0x3e, 0xe4, 0x1f, 0x77, 0xf5, 0x37, 0x00,
	0x00, 0xff, 0xff, 0x04, 0x64, 0x7e, 0xe3, 0xcb, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BuildServiceClient is the client API for BuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuildServiceClient interface {
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
	GetVersions(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	ReportCrash(ctx context.Context, in *CrashRequest, opts ...grpc.CallOption) (*CrashResponse, error)
}

type buildServiceClient struct {
	cc *grpc.ClientConn
}

func NewBuildServiceClient(cc *grpc.ClientConn) BuildServiceClient {
	return &buildServiceClient{cc}
}

func (c *buildServiceClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, "/buildserver.BuildService/Build", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) GetVersions(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/buildserver.BuildService/GetVersions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) ReportCrash(ctx context.Context, in *CrashRequest, opts ...grpc.CallOption) (*CrashResponse, error) {
	out := new(CrashResponse)
	err := c.cc.Invoke(ctx, "/buildserver.BuildService/ReportCrash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildServiceServer is the server API for BuildService service.
type BuildServiceServer interface {
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
	GetVersions(context.Context, *VersionRequest) (*VersionResponse, error)
	ReportCrash(context.Context, *CrashRequest) (*CrashResponse, error)
}

func RegisterBuildServiceServer(s *grpc.Server, srv BuildServiceServer) {
	s.RegisterService(&_BuildService_serviceDesc, srv)
}

func _BuildService_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buildserver.BuildService/Build",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_GetVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).GetVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buildserver.BuildService/GetVersions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).GetVersions(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_ReportCrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).ReportCrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buildserver.BuildService/ReportCrash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).ReportCrash(ctx, req.(*CrashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BuildService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "buildserver.BuildService",
	HandlerType: (*BuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Build",
			Handler:    _BuildService_Build_Handler,
		},
		{
			MethodName: "GetVersions",
			Handler:    _BuildService_GetVersions_Handler,
		},
		{
			MethodName: "ReportCrash",
			Handler:    _BuildService_ReportCrash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buildserver.proto",
}
